### ISSUE TITLE
sampleについて

### ISSUE THREAD

**Issue by kurema** [aozorahack/aozora2html#104]
[sample](https://github.com/aozorahack/aozora2html/tree/master/sample)の[323行目](https://github.com/aozorahack/aozora2html/blob/88ca166e7530b5895d644fdc561cb41ecd0696dc/sample/chukiichiran_kinyurei.txt#L323)、`［＃ここから○字下げ］`が漢数字「〇」ではなく丸印「○」になっています。
変換結果は以下のように無効なclassとstyleになっています。
https://github.com/aozorahack/aozora2html/blob/88ca166e7530b5895d644fdc561cb41ecd0696dc/sample/chukiichiran_kinyurei.html#L313
意図したものかもしれませんが、変換結果は変だと思います。

他に変換結果の改行コードに"\n"が混ざっています。
[プルリクエスト](https://github.com/aozorahack/aozora2html/pull/103)を参照してください。

**Comment by takahashim** [comment]
ご指摘ありがとうございます、これはもともとは https://www.aozora.gr.jp/annotation/heading.html にある例文からとったものなんですが、たしかに例文の方が良くないですよね…。

`［＃ここから３字下げ］` に変更してみます。
