### ISSUE TITLE
縦書き対応に関して

### ISSUE THREAD

**Issue by ksato9700** [aozorahack/aozora2html#13]
aozora2htmlの出力を縦書き表示できると良いと思うのですが、どのようにしたら良いかのご相談です。

世の中には幾つか縦書き対応のビューアーがあるようですが、Flashの実装はマルチプラットフォームを考えた場合はあまり良い選択肢ではないように思います。「青空縦書きリーダー」というのはCSSベースのようですが、ChromeのExtensionなのでブラウザを選んでしまいます。

Web上の記事 (e.g. https://app.codegrid.net/entry/vertical-script-1 )を読むと昨今のブラウザでは縦書きの対応がそこそこされてきているようなので、aozora2htmlが吐き出すHTMLでもCSSで縦書き対応できたら良いのかなと思いました。

ただ、本質的にはHTMLの生成とCSSの指定は別だと思うので、例えば、aozora2htmlでは外からCSSを指定・追加出来るようにしていただくことで良いのかもしれません。その場合、縦書きCSSの方は別のプロジェクトとしてaozorahackに追加ですかね。

ご意見頂けると助かります。よろしくお願い致します。

**Comment by takahashim** [comment]
これは最終的にはCSSファイルをなんとかしていただくことになりそうですが、パスは変更できても良さそうです

**Comment by ksato9700** [comment]
はい、通常のaozora.cssだとしても今は相対パス固定だと思うので、そこは指定できると助かります。こちらで適当に作ってみてPRした方が良いでしょうか？　指定項目が増えてくると configファイルみたいなもので指定したくなってきますよね..

**Comment by takahashim** [comment]
はい、そのうち大きく改変するかもですが、いつやるといった予定はないのでPRいただければ取り込みます

**Comment by ksato9700** [comment]
了解です。相変わらずRubyはよくわかっていませんが、トライしてみます。

**Comment by ksato9700** [comment]
v0.7.0でCSS指定ができるようになったのでこちらのissueはcloseします。
