### ISSUE TITLE
RuboCopのバージョンについて

### ISSUE THREAD

**Issue by gemmaro** [aozorahack/aozora2html#44]
このリポジトリには既に `.rubocop.yml` がありますが、RuboCop v1.22.0 では警告及びエラーが出ます（実行結果は末尾）。
`aozora2html.gemspec` ファイルに `rubocop` と `meowcop` が追記されていると、 `$ bundle install` から `$ bundle exec rubocop` として検査できるようになります。
つきまして適切なRuboCopとMeowCopのバージョンがわかりましたら、追記いただけますと幸いです。

想定される変更は以下：
* `aozora2html.gemspec` へのRuboCop, MeowCopの追加
  * RuboCopのバージョンによってはRuboCop Performanceの追加
    * ← RuboCopは少なくともv1.0.0以降はRuboCop Performanceを[別のgemとして切り出したようです](https://github.com/rubocop/rubocop/issues/5977)。
* `.rubocop.yml` の更新
  * `$ bundle exec rubocop --auto-gen-config` が利用できる場合、 `.rubocop-todo.yml` の追加も考えられます
* GitHub ActionsでのRuboCopにしたがった検査の追加
  * `.github/workflows/ruby.yml` への追記、または別のワークフローを追加

_ _ _

実行結果：

```shell-session
aozora2html on  master via 💎 v2.7.4 
❯ rubocop            
.rubocop.yml:59: `Style/Encoding` is concealed by line 129
.rubocop.yml:28: `Layout/SpaceBeforeBlockBraces` is concealed by line 220
.rubocop.yml:46: `Style/ClassAndModuleChildren` is concealed by line 226
.rubocop.yml: Style/MethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/VariableName has the wrong namespace - should be Naming
.rubocop.yml: Style/VariableNumber has the wrong namespace - should be Naming
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/StringConversionInInterpolation` cop has been renamed to `Lint/RedundantStringCoercion`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Style/UnneededPercentQ` cop has been renamed to `Style/RedundantPercentQ`.
(obsolete configuration found in .rubocop.yml, please update it)
`Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in .rubocop.yml, please update it)

aozora2html on  master via 💎 v2.7.4 
❯ rubocop -v  
1.22.0
```

**Comment by takahashim** [comment]
確かにこれは古いので修正しないといけないですね…。
とはいえ動作環境的にrubocopを動かすためのGemfileは別途用意した方がいいかもしれません。

**Comment by takahashim** [comment]
こちらですが、いったん現状のRuby 2.x用のバージョンをaozora2html-2.0としてリリースして、Ruby 2.7以降に対応したバージョンをaozora2html-3.xシリーズとする方向で考えています。

**Comment by takahashim** [comment]
もろもろ修正して、GitHub Actionsの方も追加しておきました。
.rubocop_todo.ymlにある課題に対応していくのは随時やっていきます。

**Comment by takahashim** [comment]
@gemmaro rubocop周りはあらかた整理して対応できたつもりです。このissueは閉じてしまって問題ないでしょうか？

**Comment by gemmaro** [comment]
はい、問題ありません。ご対応いただきありがとうございました。
